### PR TITLE
Modernize the build and cleanup the repository content

### LINKED ISSUE #1: Modernize the build and cleanup the repository content
The  Git repository content has accumulated at lot of unused parts that should be cleaned up.  It should be easier to produce p2 repositories for milestones and releases.  Dependencies should be updated and should be easier to keep up-to-date.   And it should be easier to contribute to the project via an automated setup.

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-datatools/datatools/issues/1

### CODE REVIEW

**Comment by merks** [comment]
I've done an initial build of this PR request here:

https://download.eclipse.org/datatools/updates

**Comment by merks** [comment]
@sbouchet 

I've created a pull request with all the changes.  I've also configured this job:

https://ci.eclipse.org/datatools/job/build-test

It has produced this nightly build:

https://download.eclipse.org/datatools/updates/nightly/N202305301104

I would really like to contribute a milestone build of these changes to SimRel for RC1 this week, if at all possible...

**Comment by sbouchet** [comment]
checking and validating ASAP.

**Comment by merks** [comment]
I'll do the squash and merge when you give me the green light.  Let's avoid creating merge commits in general...

**Comment by sbouchet** [comment]
yes, i agree with squash/merge strategy

**Review by sbouchet — APPROVED** [review]
overrall code LGTM. can build locally, CI build is fine, updatesite produced looks good.

**Comment by merks** [comment]
@sbouchet

So I can squash and merge?  😃 

I will provide an Oomph setup immediately afterward, update the README and such...

**Comment by sbouchet** [comment]
> @sbouchet
> 
> So I can squash and merge? smiley

Sure ! :+1: 

> 
> I will provide an Oomph setup immediately afterward, update the README and such...

**Pull request merged**
